<?xml version="1.0" encoding="utf-8"?><Database Name="MovieDatabase" Class="MovieDatabaseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\MovieDatabase.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="MoviesApplication.Properties.Settings" SettingsPropertyName="MovieDatabaseConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Genre" Member="Genres">
    <Type Name="Genre">
      <Column Name="genreId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_MovieGenre" Member="MovieGenres" ThisKey="genreId" OtherKey="genreId" Type="MovieGenre" />
    </Type>
  </Table>
  <Table Name="dbo.MovieGenre" Member="MovieGenres">
    <Type Name="MovieGenre">
      <Column Name="movieId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="genreId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Genre_MovieGenre" Member="Genre" ThisKey="genreId" OtherKey="genreId" Type="Genre" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Movy_MovieGenre" Member="Movy" ThisKey="movieId" OtherKey="movieId" Type="Movy" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movy">
      <Column Name="movieId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="releaseYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="language" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="rating" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="director" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Movy_MovieGenre" Member="MovieGenres" ThisKey="movieId" OtherKey="movieId" Type="MovieGenre" />
      <Association Name="Movy_MoviePerson" Member="MoviePersons" ThisKey="movieId" OtherKey="movieId" Type="MoviePerson" />
      <Association Name="PersonRole_Movy" Member="PersonRole" ThisKey="director" OtherKey="personRolesId" Type="PersonRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="personId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="nationality" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="birthYear" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Person_PersonRole" Member="PersonRoles" ThisKey="personId" OtherKey="personId" Type="PersonRole" />
    </Type>
  </Table>
  <Table Name="dbo.PersonRoles" Member="PersonRoles">
    <Type Name="PersonRole">
      <Column Name="personRolesId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="personId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PersonRole_Movy" Member="Movies" ThisKey="personRolesId" OtherKey="director" Type="Movy" />
      <Association Name="PersonRole_MoviePerson" Member="MoviePersons" ThisKey="personRolesId" OtherKey="personRolesId" Type="MoviePerson" />
      <Association Name="Person_PersonRole" Member="Person" ThisKey="personId" OtherKey="personId" Type="Person" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Role_PersonRole" Member="Role" ThisKey="roleId" OtherKey="roleId" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="roleId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="[Actor/Actress/Director]" Member="Actor_Actress_Director" Type="System.String" DbType="NChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Role_PersonRole" Member="PersonRoles" ThisKey="roleId" OtherKey="roleId" Type="PersonRole" />
    </Type>
  </Table>
  <Table Name="dbo.MoviePerson" Member="MoviePersons">
    <Type Name="MoviePerson">
      <Column Name="movieId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="personRolesId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Movy_MoviePerson" Member="Movy" ThisKey="movieId" OtherKey="movieId" Type="Movy" IsForeignKey="true" />
      <Association Name="PersonRole_MoviePerson" Member="PersonRole" ThisKey="personRolesId" OtherKey="personRolesId" Type="PersonRole" IsForeignKey="true" />
    </Type>
  </Table>
</Database>